name: polap-evo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.44=hdf8817f_2
  - biopython=1.85=py311h49ec1c0_2
  - blast=2.17.0=h66d330f_0
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.14.1=h332b0f4_0
  - entrez-direct=24.0=he881be0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gdbm=1.18=h0a1914f_2
  - gfortran_impl_linux-64=15.2.0=h1b0a18f_7
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - harfbuzz=12.1.0=h15599e2_0
  - htslib=1.22.1=h566b1c6_0
  - icu=75.1=he02047a_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.25.1=h3f43e3d_1
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libcblas=3.9.0=36_h0358290_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=15.2.0=hb13aed2_7
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - minimap2=2.30=h577a1d6_0
  - mummer4=4.0.1=pl5321h9948957_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.3=py311h2e04523_0
  - openssl=3.5.4=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.213=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.213=pl5321h4dac143_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.213=pl5321h503566f_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pysam=0.23.3=py311hb456a96_1
  - python=3.11.13=h9e4cc4f_0_cpython
  - python_abi=3.11=8_cp311
  - r-base=4.5.1=h14df4e6_3
  - r-cli=3.6.5=r45h3697838_1
  - r-colorspace=2.1_2=r45h54b55ab_0
  - r-data.table=1.17.8=r45h1c8cec4_1
  - r-farver=2.1.2=r45h3697838_2
  - r-ggplot2=4.0.0=r45h785f33e_0
  - r-glue=1.8.0=r45h54b55ab_1
  - r-gridextra=2.3=r45hc72bb7e_1007
  - r-gtable=0.3.6=r45hc72bb7e_1
  - r-isoband=0.2.7=r45h3697838_4
  - r-labeling=0.4.3=r45hc72bb7e_2
  - r-lifecycle=1.0.4=r45hc72bb7e_2
  - r-munsell=0.5.1=r45hc72bb7e_2
  - r-r6=2.6.1=r45hc72bb7e_1
  - r-rcolorbrewer=1.1_3=r45h785f33e_4
  - r-rlang=1.1.6=r45h3697838_1
  - r-s7=0.2.0=r45h54b55ab_1
  - r-scales=1.4.0=r45hc72bb7e_1
  - r-vctrs=0.6.5=r45h3697838_2
  - r-viridislite=0.4.2=r45hc72bb7e_3
  - r-withr=3.0.2=r45hc72bb7e_1
  - readline=8.2=h8c095d6_2
  - ruby=3.4.7=hd8161a3_0
  - samtools=1.22.1=h96c455f_0
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tzdata=2025b=h78e105d_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaggo=1.5.10=hdfd78af_1
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-evo
