name: polap-test
channels:
  - goshng
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.5.1=pyhd8ed1ab_0
  - aria2=1.37.0=hbc8128a_2
  - assembly-stats=1.0.1=h9948957_9
  - aster=1.19=h9948957_1
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - bioawk=1.0=h577a1d6_13
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_3
  - bioconductor-biostrings=2.74.0=r44h3df3fcb_1
  - bioconductor-data-packages=20250105.1=hdfd78af_0
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_2
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-ggtree=3.14.0=r44hdfd78af_0
  - bioconductor-iranges=2.40.0=r44h3df3fcb_2
  - bioconductor-s4vectors=0.44.0=r44h3df3fcb_2
  - bioconductor-treeio=1.30.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44h9ee0642_1
  - bioconductor-xvector=0.46.0=r44h15a9599_2
  - bioconductor-zlibbioc=1.52.0=r44h3df3fcb_2
  - biopython=1.83=py38h01eb140_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - blast=2.16.0=h66d330f_4
  - bowtie2=2.5.4=he96a11b_5
  - brotli-python=1.1.0=py38h17151c0_1
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.4=h3394656_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - cflye=2.9.5.1=py38he0f268d_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - clustalw=2.1=h9948957_12
  - cpython=3.8.20=py38hd8ed1ab_2
  - csvtk=0.33.0=h0d0c7ba_0
  - curl=8.12.1=h332b0f4_0
  - diamond=2.1.11=h5ca1c30_1
  - entrez-direct=22.4=he881be0_0
  - fastme=2.1.6.3=h7b50bb2_1
  - fasttree=2.1.11=h7b50bb2_5
  - flye=2.9.5=py38hd638cd3_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h36c2ea0_0
  - gawk=5.3.1=hcd3d067_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gdbm=1.18=h0a1914f_2
  - getorganelle=1.7.7.1=pyhdfd78af_0
  - gfastats=1.3.10=h077b44d_0
  - gfatools=0.5=h577a1d6_5
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=10.4.0=h76408a6_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.21=h566b1c6_1
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - iqtree=2.4.0=h503566f_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jq=1.7.1=hd590300_0
  - k8=1.2=h6618dc6_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kmer-jellyfish=2.3.1=py38h2123bcc_4
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.23.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.82.2=h2ff4ddf_1
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsanitizer=14.2.0=hed042b8_2
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.6=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - mafft=7.526=h4bc722e_0
  - make=4.4.1=hb9d3cd8_2
  - mcl=22.282=pl5321h7b50bb2_3
  - minimap2=2.28=h577a1d6_4
  - mmseqs2=17.b804f=hd6d6fdc_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - mpmath=1.3.0=pyhd8ed1ab_0
  - muscle=3.8.1551=h9948957_8
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.1=pyhd8ed1ab_0
  - newick_utils=1.6=hd747bf3_9
  - numpy=1.24.4=py38h59b608b_0
  - oniguruma=6.9.10=hb9d3cd8_0
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.4.1=h7b32b05_0
  - orthofinder=3.0.1b1=hdfd78af_0
  - ossuuid=1.6.2=h5888daf_1001
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.3=py38h01efb38_1
  - pandoc=3.6.4=ha770c72_0
  - pango=1.56.3=h861ebed_0
  - parallel=20250222=ha770c72_0
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-alien-build=2.84=pl5321h7b50bb2_0
  - perl-alien-libxml2=0.17=pl5321h577a1d6_1
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321ha770c72_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_1
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321h503566f_5
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scalar-list-utils=1.68=pl5321hb9d3cd8_1
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.024=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-test2-suite=0.000163=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.17=pl5321ha770c72_0
  - perl-xml-libxml=2.0210=pl5321hf886d80_0
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - pigz=2.8=hadc24fc_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - polap=0.4.3.7.3=hdfd78af_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - progressivemauve=snapshot_2015_02_13=h9ee0642_3
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4a871b0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=5_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h2019614_0
  - r-ape=5.8_1=r44hb79369c_0
  - r-aplot=0.2.5=r44hc72bb7e_0
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-assertthat=0.2.1=r44hc72bb7e_5
  - r-backports=1.5.0=r44hb1dbf0f_1
  - r-base=4.4.3=h9c32bc2_0
  - r-base64enc=0.1_3=r44hb1dbf0f_1007
  - r-bit=4.6.0=r44h2b5f3a1_0
  - r-bit64=4.6.0_1=r44h2b5f3a1_0
  - r-bslib=0.9.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44hb1dbf0f_1
  - r-checkmate=2.3.2=r44hdb488b9_0
  - r-cli=3.6.4=r44h93ab643_1
  - r-clipr=0.8.0=r44hc72bb7e_3
  - r-cluster=2.1.8.1=r44hb67ce94_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-conditionz=0.1.0=r44hc72bb7e_4
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-crul=1.5.0=r44h785f33e_0
  - r-curl=6.2.1=r44h2700575_0
  - r-data.table=1.17.0=r44he23165d_0
  - r-deldir=2.0_4=r44hbcb9c34_1
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-dplyr=1.1.4=r44h0d4f4ea_1
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-evaluate=1.0.3=r44hc72bb7e_0
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fastmap=1.2.0=r44ha18555a_1
  - r-fastmatch=1.1_6=r44h2b5f3a1_0
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-foreach=1.5.2=r44hc72bb7e_3
  - r-foreign=0.8_88=r44h2b5f3a1_0
  - r-formula=1.2_5=r44hc72bb7e_2
  - r-fs=1.6.5=r44h93ab643_0
  - r-generics=0.1.3=r44hc72bb7e_3
  - r-getopt=1.20.4=r44ha770c72_1
  - r-ggfun=0.1.8=r44hc72bb7e_0
  - r-ggplot2=3.5.1=r44hc72bb7e_1
  - r-ggplotify=0.1.2=r44hc72bb7e_1
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gridextra=2.3=r44hc72bb7e_1006
  - r-gridgraphics=0.5_1=r44hc72bb7e_3
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-highr=0.11=r44hc72bb7e_1
  - r-hmisc=5.2_3=r44hb67ce94_0
  - r-hms=1.1.3=r44hc72bb7e_2
  - r-htmltable=2.4.3=r44hc72bb7e_0
  - r-htmltools=0.5.8.1=r44ha18555a_1
  - r-htmlwidgets=1.6.4=r44h785f33e_3
  - r-httpcode=0.3.0=r44ha770c72_4
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-httr2=1.1.1=r44hc72bb7e_0
  - r-igraph=2.0.3=r44h510f1ce_1
  - r-interp=1.1_6=r44ha936806_1
  - r-isoband=0.2.7=r44ha18555a_3
  - r-iterators=1.0.14=r44hc72bb7e_3
  - r-jpeg=0.1_10=r44had62be2_6
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=1.9.1=r44h2b5f3a1_0
  - r-knitr=1.50=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_6=r44hb1dbf0f_1
  - r-latticeextra=0.6_30=r44hc72bb7e_3
  - r-lazyeval=0.2.2=r44hb1dbf0f_5
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_1=r44h0d28552_1
  - r-mime=0.13=r44h2b5f3a1_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-natserv=1.0.0=r44hc72bb7e_3
  - r-nlme=3.1_167=r44hb67ce94_0
  - r-nnet=7.3_20=r44h2b5f3a1_0
  - r-oai=0.4.0=r44hc72bb7e_2
  - r-openssl=2.3.2=r44he8289e2_0
  - r-optparse=1.7.5=r44hc72bb7e_1
  - r-patchwork=1.3.0=r44hc72bb7e_0
  - r-pbapply=1.7_2=r44hc72bb7e_1
  - r-phangorn=2.12.1=r44h9124c8a_1
  - r-pillar=1.10.1=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-plyr=1.8.9=r44ha18555a_1
  - r-png=0.1_8=r44h21f035c_2
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-progress=1.2.3=r44hc72bb7e_1
  - r-purrr=1.0.4=r44h2b5f3a1_0
  - r-quadprog=1.5_8=r44hc2011d3_6
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-ratelimitr=0.4.1=r44hc72bb7e_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.0.14=r44h93ab643_0
  - r-rcppeigen=0.3.4.0.2=r44hb79369c_0
  - r-readr=2.1.5=r44h0d4f4ea_1
  - r-rentrez=1.2.3=r44h785f33e_3
  - r-rex=1.2.1=r44hc72bb7e_3
  - r-rgbif=3.8.0=r44hc72bb7e_1
  - r-ritis=1.0.0=r44hc72bb7e_3
  - r-rlang=1.1.5=r44h93ab643_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-rncl=0.8.7=r44h0d4f4ea_2
  - r-rotl=3.1.0=r44hc72bb7e_2
  - r-rpart=4.1.24=r44h2b5f3a1_0
  - r-rredlist=1.0.0=r44hc72bb7e_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_0
  - r-sass=0.4.9=r44ha18555a_1
  - r-scales=1.3.0=r44hc72bb7e_1
  - r-solrium=1.2.0=r44h785f33e_3
  - r-stringi=1.8.4=r44h33cde33_3
  - r-stringr=1.5.1=r44h785f33e_1
  - r-survival=3.8_3=r44h2b5f3a1_0
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-taxize=0.10.0=r44h785f33e_0
  - r-tibble=3.2.1=r44hdb488b9_3
  - r-tidyr=1.3.1=r44h0d4f4ea_1
  - r-tidyselect=1.2.1=r44hc72bb7e_1
  - r-tidytree=0.4.6=r44hc72bb7e_1
  - r-tinytex=0.56=r44hc72bb7e_0
  - r-triebeard=0.4.1=r44ha18555a_2
  - r-tzdb=0.4.0=r44ha18555a_2
  - r-urltools=1.7.3=r44ha18555a_5
  - r-utf8=1.2.4=r44hb1dbf0f_1
  - r-uuid=1.2_1=r44hdb488b9_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridis=0.6.5=r44hc72bb7e_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-vroom=1.6.5=r44h0d4f4ea_1
  - r-wellknown=0.7.4=r44h0d4f4ea_3
  - r-whisker=0.4.1=r44hc72bb7e_2
  - r-wikidataqueryservicer=1.0.0=r44hc72bb7e_3
  - r-wikidatar=2.3.3=r44hc72bb7e_3
  - r-wikipedir=1.7.1=r44hc72bb7e_1
  - r-wikitaxa=0.4.0=r44h785f33e_3
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-wk=0.9.4=r44h93ab643_0
  - r-worrms=0.4.3=r44h785f33e_1
  - r-xfun=0.51=r44h93ab643_0
  - r-xml=3.99_0.17=r44h5bae778_2
  - r-xml2=1.3.8=r44h1bb2df6_0
  - r-yaml=2.3.10=r44hdb488b9_0
  - r-yulab.utils=0.2.0=r44hc72bb7e_0
  - r-zoo=1.8_13=r44h2b5f3a1_0
  - raxml=8.2.13=h7b50bb2_3
  - raxml-ng=1.2.2=h6747034_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_0
  - rpsbproc=0.5.0=hd6d6fdc_2
  - ruby=3.4.2=he7af4c9_0
  - samtools=1.21=h96c455f_1
  - scikit-learn=1.3.2=py38ha25d942_2
  - scipy=1.10.1=py38h32ae08f_1
  - sed=4.8=he412f7d_0
  - seqkit=2.10.0=h9ee0642_0
  - seqtk=1.4=h577a1d6_3
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - spades=4.1.0=haf24da9_0
  - sra-tools=3.2.0=h4304569_0
  - sympy=1.13.3=pyh2585a3b_104
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2020.2=h4bd325d_4
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_0
  - tzdata=2025a=h78e105d_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xmltodict=0.14.2=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaggo=1.5.10=hdfd78af_1
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb8e6e7a_1
prefix: /home/goshng/miniconda3/envs/polap-test
