name: polap-man
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.44=hdf8817f_2
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.14.1=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=hcacfade_6
  - gfortran_impl_linux-64=15.2.0=h1b0a18f_6
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=h54ccb8d_6
  - harfbuzz=12.1.0=h15599e2_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libcblas=3.9.0=36_h0358290_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_6
  - libgcc-devel_linux-64=15.2.0=h73f6952_106
  - libgcc-ng=15.2.0=h69a702a_6
  - libgfortran=15.2.0=h69a702a_6
  - libgfortran-ng=15.2.0=h69a702a_6
  - libgfortran5=15.2.0=hcd61629_6
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.2.0=h767d61c_6
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=15.2.0=hb13aed2_6
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_106
  - libstdcxx-ng=15.2.0=h4852527_6
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pandoc=3.6.4=ha770c72_0
  - pandoc-crossref=0.3.18.1=ha770c72_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.13.9=h2b335a9_100_cp313
  - python_abi=3.13=8_cp313
  - qsv=5.1.0=py313h0d07c43_0
  - r-assertthat=0.2.1=r45hc72bb7e_6
  - r-base=4.5.1=h14df4e6_3
  - r-bit=4.6.0=r45h54b55ab_1
  - r-bit64=4.6.0_1=r45h54b55ab_1
  - r-cli=3.6.5=r45h3697838_1
  - r-clipr=0.8.0=r45hc72bb7e_4
  - r-cpp11=0.5.2=r45h785f33e_2
  - r-crayon=1.5.3=r45hc72bb7e_2
  - r-dplyr=1.1.4=r45h3697838_2
  - r-ellipsis=0.3.2=r45h54b55ab_4
  - r-fansi=1.0.6=r45h54b55ab_2
  - r-generics=0.1.4=r45hc72bb7e_1
  - r-getopt=1.20.4=r45ha770c72_2
  - r-glue=1.8.0=r45h54b55ab_1
  - r-hms=1.1.3=r45hc72bb7e_3
  - r-lifecycle=1.0.4=r45hc72bb7e_2
  - r-magrittr=2.0.4=r45h54b55ab_0
  - r-optparse=1.7.5=r45hc72bb7e_2
  - r-pillar=1.11.1=r45hc72bb7e_0
  - r-pkgconfig=2.0.3=r45hc72bb7e_5
  - r-png=0.1_8=r45h6b2d295_3
  - r-prettyunits=1.2.0=r45hc72bb7e_2
  - r-progress=1.2.3=r45hc72bb7e_2
  - r-r6=2.6.1=r45hc72bb7e_1
  - r-readr=2.1.5=r45h3697838_2
  - r-rlang=1.1.6=r45h3697838_1
  - r-tibble=3.3.0=r45h54b55ab_1
  - r-tidyselect=1.2.1=r45hc72bb7e_2
  - r-tzdb=0.5.0=r45h3697838_2
  - r-utf8=1.2.6=r45h54b55ab_1
  - r-vctrs=0.6.5=r45h3697838_2
  - r-vroom=1.6.6=r45h3697838_0
  - r-withr=3.0.2=r45hc72bb7e_1
  - readline=8.2=h8c095d6_2
  - sed=4.9=h6688a6e_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tzdata=2025b=h78e105d_0
  - wayland=1.24.0=h3e06ad9_0
  - xan=0.53.0=hb17b654_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-man
