name: polap-getorganelle
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blast=2.16.0=h66d330f_5
  - bowtie2=2.5.4=he96a11b_5
  - brotli-python=1.1.0=py313h46c70d0_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - cpython=3.13.3=py313hd8ed1ab_101
  - curl=8.13.0=h332b0f4_0
  - entrez-direct=22.4=he881be0_0
  - getorganelle=1.7.7.1=pyhdfd78af_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h11186cd_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libasprintf=0.24.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.13.0=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgettextpo=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libidn2=2.3.8=ha4ef2c3_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.6=py313h17eae1a_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.5.0=h7b32b05_1
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_1
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321h503566f_5
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scalar-list-utils=1.69=pl5321hb9d3cd8_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pigz=2.8=hadc24fc_1
  - pip=25.1.1=pyh145f28c_0
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.3=hf636f53_101_cp313
  - python_abi=3.13=7_cp313
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rpsbproc=0.5.0=hd6d6fdc_3
  - scipy=1.15.2=py313h86fcf2b_0
  - spades=4.2.0=h8d6e82b_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2020.2=h4bd325d_4
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025b=h78e105d_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wget=1.21.4=hda4d442_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-getorganelle
