name: polap-ont
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - bbmap=39.33=he5f24ec_0
  - bcftools=1.22=h3a4d415_1
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - cd-hit=4.8.1=h5ca1c30_13
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h35888ee_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.0=ha770c72_1
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312hcaba1f9_1
  - graphite2=1.3.14=hecca717_2
  - grpcio=1.62.2=py312hb06c811_0
  - gsl=2.7=he838d99_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=nompi_py312ha4f8f14_101
  - harfbuzz=11.5.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libcblas=3.9.0=35_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.0=ha770c72_1
  - libfreetype6=2.14.0=h73754d4_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.1.0=h767d61c_5
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.7.0=h8261f1e_6
  - libtorch=2.3.1=cpu_generic_h970db74_0
  - libuuid=2.41.1=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mappy=2.30=py312h4711d71_0
  - markupsafe=3.0.2=py312h178313f_1
  - medaka=2.1.1=py312ha65e1bd_0
  - minimap2=2.30=h577a1d6_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.4=py312heda63a1_0
  - ont-fast5-api=4.1.3=pyhdfd78af_0
  - openjdk=24.0.2=h5755bd7_0
  - openssl=3.5.3=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parasail-python=1.3.4=py312hdcc493e_5
  - pcre2=10.46=h1321c63_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - porechop_abi=0.5.1=py312h5e9d817_0
  - progressbar33=2.4=pyhd8ed1ab_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyabpoa=1.5.4=py312h4711d71_0
  - pycparser=2.22=pyh29332c3_1
  - pysam=0.23.3=py312h47d5410_1
  - pysocks=1.7.1=pyha55dd90_7
  - pyspoa=0.3.1=py312h5e9d817_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-edlib=1.3.9.post1=py312hf731ba3_2
  - python_abi=3.12=8_cp312
  - pytorch=2.3.1=cpu_generic_py312h2f1fc2b_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - samtools=1.22.1=h96c455f_0
  - seqkit=2.10.1=he881be0_0
  - seqtk=1.5=h577a1d6_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.34=h087de78_2
  - tar=1.35=h3b78370_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yacrd=1.0.0=h790517f_5
  - zstandard=0.24.0=py312h3fa7853_1
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-ont
