name: polap-oatk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - bbmap=39.33=he5f24ec_0
  - biopython=1.85=py313h536fd9c_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - entrez-direct=22.4=he881be0_0
  - filtlong=0.3.1=h077b44d_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - gawk=5.3.1=hcd3d067_0
  - gfatools=0.5.5=h577a1d6_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - harfbuzz=11.2.1=h3beb420_0
  - hifiasm=0.25.0=h5ca1c30_0
  - hmmer=3.4=hb6cb901_4
  - htslib=1.22.1=h566b1c6_0
  - icu=75.1=he02047a_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.24.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgettextpo=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.50=h421ea60_1
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtiff=4.7.0=h8261f1e_6
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mafft=7.526=h4bc722e_0
  - minimap2=2.30=h577a1d6_0
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - ncurses=6.5=h2d0b736_3
  - ntcard=1.2.2=pl5321h077b44d_7
  - numpy=2.2.6=py313h17eae1a_0
  - oatk=1.0=h577a1d6_1
  - openjdk=23.0.2=h53dfc1b_2
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.5.3=h26f9b46_0
  - parallel=20250422=ha770c72_0
  - pcre2=10.46=h1321c63_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.13.3=hf636f53_101_cp313
  - python_abi=3.13=7_cp313
  - racon=1.5.0=h077b44d_7
  - readline=8.2=h8c095d6_2
  - rust-mdbg=1.0.1=h4ac6f70_3
  - samtools=1.22.1=h96c455f_0
  - seqkit=2.10.1=he881be0_0
  - seqtk=1.4=h577a1d6_3
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025b=h78e105d_0
  - wget=1.21.4=hda4d442_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-oatk
