name: polap-bioc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - bioconductor-annotationdbi=1.62.2=r43hdfd78af_0
  - bioconductor-biobase=2.60.0=r43ha9d7317_0
  - bioconductor-biocfilecache=2.8.0=r43hdfd78af_0
  - bioconductor-biocgenerics=0.46.0=r43hdfd78af_0
  - bioconductor-biocio=1.10.0=r43hdfd78af_0
  - bioconductor-biocparallel=1.34.2=r43hf17093f_0
  - bioconductor-biomart=2.56.1=r43hdfd78af_0
  - bioconductor-biostrings=2.68.1=r43ha9d7317_0
  - bioconductor-bsgenome=1.68.0=r43hdfd78af_0
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.26.6=r43ha9d7317_0
  - bioconductor-genbankr=1.27.0=r43hdfd78af_0
  - bioconductor-genomeinfodb=1.36.1=r43hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-genomicalignments=1.36.0=r43ha9d7317_0
  - bioconductor-genomicfeatures=1.52.1=r43hdfd78af_0
  - bioconductor-genomicranges=1.52.0=r43ha9d7317_0
  - bioconductor-iranges=2.34.1=r43ha9d7317_0
  - bioconductor-keggrest=1.40.0=r43hdfd78af_0
  - bioconductor-matrixgenerics=1.12.2=r43hdfd78af_0
  - bioconductor-rhtslib=2.2.0=r43ha9d7317_0
  - bioconductor-rsamtools=2.16.0=r43hf17093f_0
  - bioconductor-rtracklayer=1.60.0=r43ha9d7317_0
  - bioconductor-s4arrays=1.0.4=r43ha9d7317_0
  - bioconductor-s4vectors=0.38.1=r43ha9d7317_0
  - bioconductor-summarizedexperiment=1.30.2=r43hdfd78af_0
  - bioconductor-variantannotation=1.46.0=r43ha9d7317_0
  - bioconductor-xvector=0.40.0=r43ha9d7317_0
  - bioconductor-zlibbioc=1.46.0=r43ha9d7317_0
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cd-hit=4.8.1=h5ca1c30_13
  - curl=8.14.1=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_3
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_3
  - graphite2=1.3.14=h5888daf_0
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_3
  - harfbuzz=11.3.2=hbb57e21_0
  - icu=75.1=he02047a_0
  - jq=1.8.1=h73b1eb8_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=15.1.0=h4c094af_103
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libpng=1.6.50=h943b412_0
  - libsanitizer=15.1.0=h97b714f_3
  - libsqlite=3.50.3=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_103
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - oniguruma=6.9.10=hb9d3cd8_0
  - openssl=3.5.1=h7b32b05_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.45=hc749103_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.4=h537e5f6_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.13.5=hec9711d_102_cp313
  - python_abi=3.13=8_cp313
  - pyyaml=6.0.2=py313h8060acc_2
  - r-askpass=1.2.1=r43h2b5f3a1_0
  - r-assertthat=0.2.1=r43hc72bb7e_5
  - r-base=4.3.3=h65010dc_18
  - r-bh=1.87.0_1=r43hc72bb7e_0
  - r-bit=4.6.0=r43h2b5f3a1_0
  - r-bit64=4.6.0_1=r43h2b5f3a1_0
  - r-bitops=1.0_9=r43h2b5f3a1_0
  - r-blob=1.2.4=r43hc72bb7e_2
  - r-cachem=1.1.0=r43hb1dbf0f_1
  - r-cli=3.6.5=r43h93ab643_0
  - r-codetools=0.2_20=r43hc72bb7e_1
  - r-cpp11=0.5.2=r43h785f33e_1
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-curl=6.2.2=r43h2700575_0
  - r-dbi=1.2.3=r43hc72bb7e_1
  - r-dbplyr=2.5.0=r43hc72bb7e_1
  - r-digest=0.6.37=r43h0d4f4ea_0
  - r-dplyr=1.1.4=r43h0d4f4ea_1
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-fastmap=1.2.0=r43ha18555a_1
  - r-filelock=1.0.3=r43hb1dbf0f_1
  - r-formatr=1.14=r43hc72bb7e_2
  - r-futile.logger=1.4.3=r43hc72bb7e_1006
  - r-futile.options=1.0.1=r43hc72bb7e_1005
  - r-generics=0.1.4=r43hc72bb7e_0
  - r-getopt=1.20.4=r43ha770c72_1
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-hms=1.1.3=r43hc72bb7e_2
  - r-httr=1.4.7=r43hc72bb7e_1
  - r-jsonlite=2.0.0=r43h2b5f3a1_0
  - r-lambda.r=1.2.4=r43hc72bb7e_4
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-matrix=1.6_5=r43he966344_1
  - r-matrixstats=1.5.0=r43h2b5f3a1_0
  - r-memoise=2.0.1=r43hc72bb7e_3
  - r-mime=0.13=r43h2b5f3a1_0
  - r-openssl=2.3.3=r43he8289e2_0
  - r-optparse=1.7.5=r43hc72bb7e_1
  - r-pillar=1.11.0=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-plogr=0.2.0=r43hc72bb7e_1006
  - r-png=0.1_8=r43h21f035c_2
  - r-prettyunits=1.2.0=r43hc72bb7e_1
  - r-progress=1.2.3=r43hc72bb7e_1
  - r-purrr=1.1.0=r43h54b55ab_0
  - r-r6=2.6.1=r43hc72bb7e_0
  - r-rappdirs=0.3.3=r43hb1dbf0f_3
  - r-rcurl=1.98_1.16=r43he8228da_1
  - r-restfulr=0.0.15=r43h56115f1_3
  - r-rjson=0.2.23=r43h93ab643_0
  - r-rlang=1.1.6=r43h93ab643_0
  - r-rsqlite=2.4.2=r43h3697838_0
  - r-snow=0.4_4=r43hc72bb7e_3
  - r-stringi=1.8.7=r43h3c328a7_0
  - r-stringr=1.5.1=r43h785f33e_1
  - r-sys=3.4.3=r43h2b5f3a1_0
  - r-tibble=3.3.0=r43h2b5f3a1_0
  - r-tidyr=1.3.1=r43h0d4f4ea_1
  - r-tidyselect=1.2.1=r43hc72bb7e_1
  - r-utf8=1.2.6=r43h2b5f3a1_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-withr=3.0.2=r43hc72bb7e_0
  - r-xml=3.99_0.17=r43h5bae778_2
  - r-xml2=1.3.8=r43h1bb2df6_0
  - r-yaml=2.3.10=r43hdb488b9_0
  - readline=8.2=h8c095d6_2
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - toml=0.10.2=pyhd8ed1ab_1
  - tomlkit=0.13.3=pyha770c72_0
  - tzdata=2025b=h78e105d_0
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhe01879c_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-bioc
