name: polap-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - archspec=0.2.3=pyhd8ed1ab_0
  - aria2=1.37.0=h347180d_1
  - attrs=23.2.0=pyh71513ae_0
  - bash=5.0.018=h0a1914f_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bedtools=2.31.1=hf5e1c6e_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - bioawk=1.0=he4a0461_9
  - bioconductor-ggtree=3.10.0=r43hdfd78af_0
  - bioconductor-treeio=1.26.0=r43hdfd78af_1
  - blas=1.1=openblas
  - blast=2.15.0=pl5321h6f7f691_1
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.26.0=hd590300_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.7.4=py310h06a4308_0
  - cffi=1.16.0=py310h2fee648_0
  - chardet=5.2.0=py310hff52083_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - clustalw=2.1=h4ac6f70_9
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.3.0=py310hff52083_0
  - conda-build=24.7.1=py310h06a4308_0
  - conda-index=0.4.0=pyhd8ed1ab_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - csvtk=0.29.0=h9ee0642_0
  - curl=8.7.1=hca28451_0
  - diamond=2.1.9=h43eeafb_0
  - distro=1.9.0=pyhd8ed1ab_0
  - entrez-direct=16.2=he881be0_1
  - expat=2.5.0=hcb278e6_1
  - fastme=2.1.6.1=h031d066_3
  - fasttree=2.1.11=h031d066_2
  - filelock=3.13.3=pyhd8ed1ab_0
  - flye=2.9.3=py310h2b6aa90_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozendict=2.4.2=py310h5eee18b_0
  - gawk=5.3.0=ha916aea_0
  - gcc_impl_linux-64=11.2.0=h82a94d6_16
  - gcc_linux-64=11.2.0=h39a9532_10
  - gettext=0.21.1=h27087fc_0
  - gfastats=1.3.6=hdcf5f25_3
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - gfortran_linux-64=11.2.0=h777b47f_10
  - glib=2.78.4=hfc55251_0
  - glib-tools=2.78.4=hfc55251_0
  - gmp=6.3.0=h59595ed_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=11.2.0=h82a94d6_16
  - gxx_linux-64=11.2.0=hacbe6df_10
  - harfbuzz=8.3.0=h3d44ed6_0
  - htslib=1.6=0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - iqtree=2.2.6=h21ec9f0_0
  - jellyfish=2.2.10=h6bb024c_1
  - jemalloc=5.3.0=hcb278e6_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - k8=0.2.5=hdcf5f25_4
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libblas=3.9.0=21_linux64_openblas
  - libcblas=3.9.0=21_linux64_openblas
  - libcurl=8.7.1=hca28451_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=11.2.0=h0952999_16
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=h783c2da_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjemalloc=5.3.0=hcb278e6_0
  - liblapack=3.9.0=21_linux64_openblas
  - liblief=0.14.1=hac33072_1
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py310h39ff949_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.42=h2797004_0
  - libsanitizer=11.2.0=he4da1e4_16
  - libsolv=0.7.28=hfc55251_2
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=11.2.0=h0952999_16
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mafft=7.520=h031d066_3
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.5=py310h2372a71_0
  - mcl=22.282=pl5321h031d066_1
  - menuinst=2.0.2=py310hff52083_0
  - minimap2=2.26=he4a0461_2
  - mmseqs2=15.6f452=pl5321h6a68c12_0
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - mpfr=4.2.1=h9458935_0
  - mpi=1.0=openmpi
  - muscle=3.8.1551=h7d875b9_6
  - ncbi-vdb=3.0.10=hdbdd923_0
  - ncurses=6.4=h59595ed_2
  - numpy=1.26.4=py310hb13e2d6_0
  - openblas=0.3.26=pthreads_h7a3da1a_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.2.1=hd590300_1
  - orthofinder=2.5.5=hdfd78af_2
  - ossuuid=1.6.2=hf484d3e_1000
  - packaging=24.0=pyhd8ed1ab_0
  - pango=1.50.14=ha41ecd1_2
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.42=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-alien-build=2.48=pl5321hec16e2b_0
  - perl-alien-libxml2=0.17=pl5321hec16e2b_0
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321ha770c72_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321h166bdaf_0
  - perl-compress-raw-zlib=2.202=pl5321h166bdaf_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-encode=3.19=pl5321h166bdaf_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321hdbdd923_2
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_0
  - perl-json-xs=2.34=pl5321h4ac6f70_6
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_2
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-scalar-list-utils=1.63=pl5321h166bdaf_0
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-storable=3.15=pl5321h166bdaf_0
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.016=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-test2-suite=0.000145=pl5321hdfd78af_0
  - perl-threaded=5.32.1=hdfd78af_1
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.17=pl5321ha770c72_0
  - perl-xml-libxml=2.0124=0
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkginfo=1.10.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - psutil=5.9.8=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-lief=0.14.1=py310h76e45a6_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310h2372a71_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=hd12c33a_1_cpython
  - python-libarchive-c=5.1=py310hff52083_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - r-ape=5.7_1=r43h08d816e_1
  - r-aplot=0.2.2=r43hc72bb7e_0
  - r-assertthat=0.2.1=r43hc72bb7e_4
  - r-base=4.3.1=h1ae530e_0
  - r-bit=4.0.5=r43h57805ef_1
  - r-bit64=4.0.5=r43h57805ef_2
  - r-cachem=1.0.8=r43h57805ef_1
  - r-cli=3.6.2=r43ha503ecb_0
  - r-clipr=0.8.0=r43hc72bb7e_2
  - r-colorspace=2.1_0=r43h57805ef_1
  - r-cpp11=0.4.7=r43hc72bb7e_0
  - r-crayon=1.5.2=r43hc72bb7e_2
  - r-digest=0.6.35=r43ha503ecb_0
  - r-dplyr=1.1.4=r43h0d4f4ea_1
  - r-ellipsis=0.3.2=r43h57805ef_2
  - r-fansi=1.0.6=r43h57805ef_0
  - r-farver=2.1.1=r43ha503ecb_2
  - r-fastmap=1.1.1=r43ha503ecb_1
  - r-fs=1.6.3=r43ha503ecb_0
  - r-generics=0.1.3=r43hc72bb7e_2
  - r-getopt=1.20.4=r43ha770c72_0
  - r-ggfun=0.1.4=r43hc72bb7e_0
  - r-ggplot2=3.5.0=r43hc72bb7e_0
  - r-ggplotify=0.1.2=r43hc72bb7e_0
  - r-glue=1.7.0=r43h57805ef_0
  - r-gridgraphics=0.5_1=r43hc72bb7e_2
  - r-gtable=0.3.4=r43hc72bb7e_0
  - r-hms=1.1.3=r43hc72bb7e_1
  - r-isoband=0.2.7=r43ha503ecb_2
  - r-jsonlite=1.8.8=r43h57805ef_0
  - r-labeling=0.4.3=r43hc72bb7e_0
  - r-lattice=0.22_6=r43h57805ef_0
  - r-lazyeval=0.2.2=r43h57805ef_4
  - r-lifecycle=1.0.4=r43hc72bb7e_0
  - r-magrittr=2.0.3=r43h57805ef_2
  - r-mass=7.3_60=r43h57805ef_1
  - r-matrix=1.6_5=r43h316c678_0
  - r-memoise=2.0.1=r43hc72bb7e_2
  - r-mgcv=1.9_1=r43h316c678_0
  - r-munsell=0.5.1=r43hc72bb7e_0
  - r-nlme=3.1_164=r43h61816a4_0
  - r-optparse=1.7.5=r43hc72bb7e_1
  - r-patchwork=1.2.0=r43hc72bb7e_0
  - r-pillar=1.9.0=r43hc72bb7e_1
  - r-pkgconfig=2.0.3=r43hc72bb7e_3
  - r-prettyunits=1.2.0=r43hc72bb7e_0
  - r-progress=1.2.3=r43hc72bb7e_0
  - r-purrr=1.0.2=r43h57805ef_0
  - r-r6=2.5.1=r43hc72bb7e_2
  - r-rcolorbrewer=1.1_3=r43h785f33e_2
  - r-rcpp=1.0.12=r43h7df8631_0
  - r-readr=2.1.5=r43h0d4f4ea_1
  - r-rlang=1.1.3=r43ha503ecb_0
  - r-scales=1.3.0=r43hc72bb7e_0
  - r-stringi=1.8.3=r43h9facbd6_0
  - r-stringr=1.5.1=r43h785f33e_1
  - r-tibble=3.2.1=r43h57805ef_2
  - r-tidyr=1.3.1=r43h0d4f4ea_1
  - r-tidyselect=1.2.0=r43hc72bb7e_1
  - r-tidytree=0.4.6=r43hc72bb7e_0
  - r-tzdb=0.4.0=r43ha503ecb_1
  - r-utf8=1.2.4=r43h57805ef_0
  - r-vctrs=0.6.5=r43ha503ecb_0
  - r-viridislite=0.4.2=r43hc72bb7e_1
  - r-vroom=1.6.5=r43ha503ecb_0
  - r-withr=3.0.0=r43hc72bb7e_0
  - r-yulab.utils=0.1.4=r43hc72bb7e_0
  - raxml=8.2.13=h031d066_0
  - raxml-ng=1.2.1=h6d1f11b_0
  - readline=8.2=h8228510_1
  - referencing=0.34.0=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - ripgrep=14.1.0=he8a937b_0
  - rpds-py=0.18.0=py310hcb5633a_0
  - ruamel.yaml=0.18.6=py310h2372a71_0
  - ruamel.yaml.clib=0.2.8=py310h2372a71_0
  - samtools=1.6=hc3601fc_10
  - scipy=1.12.0=py310hb13e2d6_2
  - sed=4.8=he412f7d_0
  - seqkit=2.7.0=h9ee0642_0
  - seqtk=1.4=he4a0461_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sra-tools=3.0.10=h9f5acd7_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hfc55251_0
prefix: /home/goshng/miniconda3/envs/polap-dev
