name: polap-polish
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa-mem2
  - cmake=3.26
  - fmlrc2
  - gcc=12
  - gfatools
  - git
  - gxx=12
  - make
  - merqury
  - meryl
  - minimap2
  - ninja
  - polypolish
  - python
  - r-base
  - ropebwt2
  - samtools
  - seqtk
  - zlib
  - bowtie2
prefix: /home/goshng/miniconda3/envs/polap-polish
