name: polap-fmlrc
channels:
  - kbchoi
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2019.11.28=py27h8c360ce_1
  - fmlrc=1.0.0=h4ac6f70_5
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=25_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libzlib=1.2.13=h4ab18f5_6
  - msbwt=0.2.9=py27_0
  - ncurses=6.5=he02047a_1
  - numpy=1.16.5=py27h95a1406_0
  - openssl=1.1.1w=hd590300_0
  - pip=20.1.1=pyh9f0ad1d_0
  - pysam=0.20.0=py27h7835474_0
  - python=2.7.15=h5a48372_1011_cpython
  - python_abi=2.7=1_cp27mu
  - readline=8.2=h8228510_1
  - ropebwt2=r187=he4a0461_9
  - setuptools=44.0.0=py27_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
prefix: /home/goshng/miniconda3/envs/polap-fmlrc
