name: polap-mbg
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libzlib=1.3.1=hb9d3cd8_2
  - mbg=1.0.16=hdcf5f25_1
prefix: /home/goshng/miniconda3/envs/polap-mbg
