name: polap-sim
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=3=2_broadwell
  - alsa-lib=1.2.14=hb9d3cd8_0
  - augustus=3.5.0=pl5321h9716f88_9
  - badread=0.4.1=pyhdfd78af_0
  - bamtools=2.5.3=he132191_0
  - bbmap=39.33=he5f24ec_0
  - bedtools=2.31.1=h13024bc_3
  - biopython=1.85=py39h8cd3c5a_1
  - blast=2.17.0=h66d330f_0
  - boost-cpp=1.85.0=h3c6214e_4
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.0.9=py39h5a03fae_8
  - busco=6.0.0=pyhdfd78af_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cdbtools=0.99=h077b44d_12
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - clustalw=2.1=h9948957_12
  - contourpy=1.3.0=py39h74842e3_2
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dendropy=5.0.8=pyhdfd78af_1
  - diamond=2.1.13=h13889ed_0
  - dnspython=2.7.0=pyhff2d567_1
  - entrez-direct=24.0=he881be0_0
  - fasttree=2.2.0=h7b50bb2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gawk=5.3.1=hcd3d067_0
  - genometools-genometools=1.6.5=py39h096c0ac_4
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.8=hbf7d49c_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.5.0=h15599e2_0
  - hmmer=3.4=h503566f_3
  - hpack=4.1.0=pyhd8ed1ab_0
  - htseq=2.0.9=py39h918f1d6_0
  - htslib=1.22.1=h566b1c6_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jsoncpp=1.9.6=hf42df4d_1
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - last=1642=h5ca1c30_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libamd=3.3.3=haaf9dc3_7100102
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcblas=3.9.0=35_h0358290_openblas
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libcolamd=3.3.4=h32481e8_7100102
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libcxsparse=4.4.1=h32481e8_7100102
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libklu=2.3.5=hf24d653_7100102
  - liblapack=3.9.0=35_h47877c9_openblas
  - libldl=3.3.2=h32481e8_7100102
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopenssl-static=3.5.3=hb03c661_1
  - libparu=1.0.0=h17147ab_7100102
  - libpng=1.6.50=h421ea60_1
  - librbio=4.3.4=h32481e8_7100102
  - libspex=3.2.3=had10066_7100102
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libtiff=4.7.0=h8261f1e_6
  - libumfpack=6.3.5=heb53515_7100102
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.1=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lp_solve=5.5.2.11=hd590300_0
  - mafft=7.526=h4bc722e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - metaeuk=7.bba0d80=pl5321hd6d6fdc_2
  - metis=5.1.0=hd0bcaf9_1007
  - minimap2=2.30=h577a1d6_0
  - miniprot=0.18=h577a1d6_0
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - munkres=1.1.4=pyhd8ed1ab_1
  - muscle=3.8.1551=h9948957_9
  - mysql-connector-c=6.1.11=h659d440_1008
  - nanosim=3.2.3=hdfd78af_1
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - numpy=1.23.5=py39h3d75532_0
  - openjdk=24.0.2=h5755bd7_0
  - openjpeg=2.5.3=h55fea9a_1
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.5.3=h26f9b46_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h1b6b32d_0
  - pango=1.56.4=hadf4263_0
  - parallel=20250822=ha770c72_0
  - pasta=1.9.3=py39h640ec12_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pbsim3=3.0.5=h9948957_2
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.46=h1321c63_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-app-cpanminus=1.7048=pl5321hd8ed1ab_0
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-method-modifiers=2.13=pl5321ha770c72_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.213=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.213=pl5321h4dac143_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-dbi=1.647=pl5321hb03c661_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.213=pl5321h503566f_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-moo=2.005004=pl5321ha770c72_0
  - perl-parallel-forkmanager=2.04=pl5321hdfd78af_0
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-role-tiny=2.002004=pl5321ha770c72_0
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-sub-quote=2.006006=pl5321ha770c72_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-yaml=1.30=pl5321hdfd78af_0
  - piecewise-regression=1.1.2=pyhd8ed1ab_0
  - pillow=11.3.0=py39h15c0740_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pplacer=1.1.alpha20=hd563303_0
  - prank=170427=h9948957_1
  - prodigal=2.6.3=h577a1d6_11
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybedtools=0.12.0=py39h475c85d_0
  - pycparser=2.22=pyh29332c3_1
  - pymongo=4.13.2=py39h818bca1_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pysam=0.23.3=py39hdd5828d_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-edlib=1.3.9.post1=py39h2de1943_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - raxml=8.2.13=h7b50bb2_3
  - readline=8.2=h8c095d6_2
  - regex=2025.7.34=py39hd399759_0
  - requests=2.32.5=pyhd8ed1ab_0
  - sam2pairwise=1.0.0=h9948957_1
  - samtools=1.22.1=h96c455f_0
  - scikit-learn=0.23.2=py39hf3c863f_3
  - scipy=1.13.1=py39haf93ffa_0
  - sepp=4.5.6=py39hbcbf7aa_1
  - seqkit=2.10.1=he881be0_0
  - seqtk=1.5=h577a1d6_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlite=3.50.4=hbc0de68_0
  - statsmodels=0.14.5=py39h7c0b2d6_0
  - suitesparse=7.10.1=ha0f6916_7100102
  - sysroot_linux-64=2.34=h087de78_2
  - tar=1.35=h3b78370_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - ucsc-fatotwobit=482=hdc0a859_0
  - ucsc-twobitinfo=482=hdc0a859_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-sim
