name: polap-ncbitools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - blast
  - entrez-direct
  - sra-tools
  - busco
  - pigz
prefix: /home/goshng/miniconda3/envs/polap-ncbitools
