name: polap-pmat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - apptainer=1.4.0=h26d8a74_0
  - attr=2.5.1=h166bdaf_1
  - blast=2.16.0=h66d330f_5
  - boost-cpp=1.85.0=h3c6214e_4
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - canu=2.3=h3fb4750_1
  - cni=1.0.1=ha975731_1
  - cni-plugins=1.3.0=ha8f183a_0
  - curl=8.13.0=h332b0f4_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.16.2=h3c4dab8_0
  - entrez-direct=22.4=he881be0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - fuse-overlayfs=1.15=hb9d3cd8_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - glib=2.84.2=h6287aef_0
  - glib-tools=2.84.2=h4833e2c_0
  - gnuplot=5.4.10=hb1719d7_0
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=11.2.1=h3beb420_0
  - htslib=1.21=h566b1c6_1
  - icu=75.1=he02047a_0
  - jq=1.7.1=hd590300_0
  - k8=1.2=h6618dc6_3
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=h75ea233_4
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libcap=2.75=h39aace5_0
  - libclang-cpp20.1=20.1.5=default_h1df26ce_1
  - libclang13=20.1.5=default_he06ed0a_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libfuse=3.10.4=h1869db9_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libllvm20=20.1.5=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - libseccomp=2.4.4=hd590300_4
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libtiff=4.7.0=hf01ce69_5
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - minimap2=2.29=h577a1d6_0
  - mpg123=1.32.9=hc50e24c_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - nextdenovo=2.5.2=py312h4e9d295_6
  - nspr=4.36=h5888daf_0
  - nss=3.111=h159eef7_0
  - oniguruma=6.9.10=hb9d3cd8_0
  - openjdk=23.0.2=h53dfc1b_2
  - openldap=2.6.9=he970967_0
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h9ac818e_1
  - paralleltask=0.1.1=pyhd8ed1ab_0
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_1
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-filesys-df=0.92=pl5321h7b50bb2_9
  - perl-io-compress=2.201=pl5321h503566f_5
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scalar-list-utils=1.69=pl5321hb9d3cd8_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hac146a9_1
  - python=3.12.10=h9e4cc4f_0_cpython
  - python_abi=3.12=7_cp312
  - qt-main=5.15.15=hea1682b_4
  - readline=8.2=h8c095d6_2
  - rpsbproc=0.5.0=hd6d6fdc_3
  - samtools=1.21=h96c455f_1
  - setuptools=80.8.0=pyhff2d567_0
  - squashfs-tools=4.6.1=hc12fc2f_2
  - squashfuse=0.6.1=hc12fc2f_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025b=h78e105d_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/goshng/miniconda3/envs/polap-pmat
