name: polap-tippo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _pytorch_select=0.1=cpu_0
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.5.1=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - bioconductor-biocgenerics=0.46.0=r43hdfd78af_0
  - bioconductor-biostrings=2.68.1=r43ha9d7317_0
  - bioconductor-data-packages=20250401=hdfd78af_0
  - bioconductor-genomeinfodb=1.36.1=r43hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-iranges=2.34.1=r43ha9d7317_0
  - bioconductor-s4vectors=0.38.1=r43ha9d7317_0
  - bioconductor-xvector=0.40.0=r43ha9d7317_0
  - bioconductor-zlibbioc=1.46.0=r43ha9d7317_0
  - biopython=1.83=py38h01eb140_0
  - blas=1.0=mkl
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - cffi=1.17.0=py38heb5c249_0
  - curl=8.8.0=he654da7_1
  - expat=2.7.0=h5888daf_0
  - flye=2.9.5=py38hd638cd3_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_2
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_2
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphaligner=1.0.17=hd03093a_0
  - graphite2=1.3.13=h59595ed_1003
  - gxx_impl_linux-64=15.1.0=h6a1bac1_2
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - intel-openmp=2019.4=243
  - joblib=0.17.0=py_0
  - jq=1.7.1=hd590300_0
  - k8=1.2=h6618dc6_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.20=hd590300_0
  - libdivsufsort=2.0.2=h7b50bb2_10
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=15.1.0=h4c094af_102
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.80.2=hf974151_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - libllvm10=10.0.1=he513fc3_3
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libmklml=2019.0.5=h06a4308_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libsanitizer=15.1.0=h97b714f_2
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_102
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.35.0=py38h4630a5e_1
  - make=4.4.1=hb9d3cd8_2
  - mcl=22.282=pl5321h7b50bb2_3
  - minimap2=2.26=he4a0461_2
  - mkl=2020.2=256
  - ncurses=6.5=h2d0b736_3
  - ninja=1.12.1=hff21bea_1
  - numba=0.52.0=py38h51da96c_0
  - numpy=1.19.5=py38h8246c76_3
  - oniguruma=6.9.10=hb9d3cd8_0
  - openssl=3.5.0=h7b32b05_1
  - pango=1.54.0=h4c5309f_1
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyhd8ed1ab_0
  - python=3.8.19=hd12c33a_0_cpython
  - python_abi=3.8=7_cp38
  - pytorch=1.7.1=cpu_py38h6a09485_0
  - pyyaml=6.0.2=py38h2019614_0
  - r-base=4.3.3=hf0d99cb_1
  - r-bitops=1.0_9=r43h2b5f3a1_0
  - r-cli=3.6.5=r43h93ab643_0
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-cpp11=0.5.2=r43h785f33e_1
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-ggplot2=3.4.4=r43hc72bb7e_0
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-igraph=1.5.1=r43hb147323_1
  - r-isoband=0.2.7=r43ha18555a_3
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60.0.1=r43hb1dbf0f_1
  - r-matrix=1.6_5=r43he966344_1
  - r-mgcv=1.9_3=r43h2ae2be5_0
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-nlme=3.1_168=r43hb67ce94_0
  - r-pheatmap=1.0.12=r43hc72bb7e_5
  - r-pillar=1.10.2=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-r6=2.6.1=r43hc72bb7e_0
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-rcurl=1.98_1.16=r43h6b349a7_0
  - r-rlang=1.1.6=r43h93ab643_0
  - r-scales=1.4.0=r43hc72bb7e_0
  - r-stringdist=0.9.10=r43h57805ef_1
  - r-tibble=3.2.1=r43hdb488b9_3
  - r-utf8=1.2.5=r43h2b5f3a1_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-withr=3.0.2=r43hc72bb7e_0
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.0.2=py38h1561384_0
  - scipy=1.9.1=py38hea3f02b_0
  - sed=4.9=h6688a6e_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - skorch=0.9.0=pyh7b7c402_0
  - spoa=4.1.4=hdcf5f25_2
  - sysroot_linux-64=2.17=h0157908_18
  - tabulate=0.9.0=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiara=1.0.3=pyhd8ed1ab_0
  - tipp=1.3.0=py38pl5321h077b44d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_0
  - tqdm=4.54.1=pyhd8ed1ab_1
  - trf=4.09.1=h7b50bb2_7
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xmltodict=0.14.2=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/goshng/miniconda3/envs/polap-tippo
