name: polap-fmlrc2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - fmlrc2=0.1.7=hb7a5142_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_2
  - gsl=2.7=he838d99_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=15.1.0=h4c094af_102
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libsanitizer=15.1.0=h97b714f_2
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libzlib=1.2.13=h4ab18f5_6
  - openssl=1.1.1w=hd590300_0
  - rust=1.77.2=h70c747d_1
  - rust-std-x86_64-unknown-linux-gnu=1.77.2=h2c6d0dc_1
  - starcode=1.4=h7b50bb2_6
  - sysroot_linux-64=2.17=h0157908_18
  - tzdata=2025b=h78e105d_0
  - zlib=1.2.13=h4ab18f5_6
prefix: /home/goshng/miniconda3/envs/polap-fmlrc2
